import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { ReactElement } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { Icon } from "@iconify/react";
import tidalIcon from "@iconify/icons-simple-icons/tidal";
import { motion } from "framer-motion";
import React from "react";
import ReactDOM from "react-dom";
import { SocialIcon } from "react-social-icons";

import {
  faItunes,
  faSpotify,
  faYoutube
} from "@fortawesome/free-brands-svg-icons";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Xusted Music</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.thirteen}>
            <h1 className={inter.className}>XUSTED</h1>
            <h4 className={inter.className}>music</h4>
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://listen.tidal.com/album/255879569"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Maze <span>-&gt;</span>
            </h2>
            <div className={styles.container}>
              <Image
                src="/maze.png"
                alt="maze"
                width={100}
                height={100}
                priority
              />
            </div>
          </a>

          <a
            href="https://listen.tidal.com/album/210068928"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Busted <span>-&gt;</span>
            </h2>
            <div className={styles.container}>
              <Image
                src="/busted.png"
                alt="busted"
                width={100}
                height={100}
                priority
              />
            </div>
          </a>

          <a
            href="https://listen.tidal.com/album/201461335"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Receptor <span>-&gt;</span>
            </h2>
            <div className={styles.container}>
              <Image
                src="/receptor.png"
                alt="receptor"
                width={100}
                height={100}
                priority
              />
            </div>
          </a>

          <a
            href="https://listen.tidal.com/album/176048444"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Tyo Oyt <span>-&gt;</span>
            </h2>
            <div className={styles.container}>
              <Image
                src="/tyooyt.png"
                alt="tyo oyt"
                width={100}
                height={100}
                priority
              />
            </div>
          </a>

          <a
            href="https://listen.tidal.com/album/149961226"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Awake Slumber<span>-&gt;</span>
            </h2>
            <div className={styles.container}>
              <Image
                src="/AwakeSlumber.png"
                alt="Awake slumber"
                width={100}
                height={100}
                priority
              />
            </div>
          </a>

          <a
            href="https://listen.tidal.com/album/139228896"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Tunnel Visions <span>-&gt;</span>
            </h2>
            <div className={styles.container}>
              <Image
                src="/TunnelVisions.png"
                alt="Tunnel visions"
                width={100}
                height={100}
                priority
              />
            </div>
          </a>

          <a
            href="https://listen.tidal.com/album/125553413"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Ice Picker <span>-&gt;</span>
            </h2>
            <div className={styles.container}>
              <Image
                src="/IcePicker.png"
                alt="Ice Pickert"
                width={100}
                height={100}
                priority
              />
            </div>
          </a>
        </div>
        <div className={styles.container}>
          <a href="https://www.youtube.com/channel/UCUJrqOFKzMfDCGenCvLLwdQ">
            <FontAwesomeIcon
              icon={faYoutube}
              beat
              size="2xl"
              style={{
                paddingLeft: "12px",
                paddingRight: "12px",
                marginBottom: "25px",
              }}
            />
          </a>
          <a href="https://open.spotify.com/artist/11lVHxCjt7gVjwwPvPC8mG">
            <FontAwesomeIcon
              icon={faSpotify}
              bounce
              size="2xl"
              style={{
                paddingLeft: "12px",
                paddingRight: "12px",
                marginBottom: "25px",
              }}
            />
          </a>
          <a href="https://music.apple.com/se/artist/xusted/1491482184">
            <FontAwesomeIcon
              icon={faItunes}
              shake
              size="2xl"
              style={{
                paddingLeft: "12px",
                paddingRight: "12px",
                marginBottom: "25px",
              }}
            />
          </a>
          <a href="https://listen.tidal.com/artist/17716554">
            <Icon
              icon={tidalIcon}
              width="60"
              style={{
                paddingLeft: "12px",
                paddingRight: "12px",
                marginBottom: "23px",
              }}
            />
          </a>
        </div>
        <motion.div
          initial={{
            x: 500,
            opacity: 0,
            scale: 0.2,
          }}
          animate={{
            x: 0,
            opacity: 1,
            scale: 1.5,
          }}
          transition={{
            duration: 4,
          }}
          className="flex flex-row items-center text-gray-300 cursor-pointer"
        >
          <SocialIcon
            className="cursor-pointer"
            network="email"
            fgColor="black"
            bgColor="transparent"
          />
        </motion.div>
        <div className={inter.className}>
          <br/>
          <p>© Xusted 2023</p>
        </div>
      </main>
    </>
  );
}
